### PR TITLE
Sync LICENSE file to same as in metadata.json (Apache-2.0)

### PR DESCRIPTION
**Pull request by juniorsysadmin**
LICENSE file is MIT but metadata.json has had Apache-2.0 for quite
some time

### CODE REVIEW

**Comment by liamjbennett** [comment]
+1

**Comment by juniorsysadmin** [comment]
Note: One committer @liamjbennett and one approval for change in LICENSE

**Comment by juniorsysadmin** [comment]
Ready for approval/merge

**Comment by juniorsysadmin** [comment]
> Note: One committer @liamjbennett and one approval for change in LICENSE

Correction: There is one other committer. Their commit changed a year value in the LICENSE file.

**Comment by juniorsysadmin** [comment]
@stack72 Do we have your approval to change the LICENSE for this from MIT to Apache-2.0 ?

**Comment by juniorsysadmin** [comment]
> @stack72 Do we have your approval to change the LICENSE for this from MIT to Apache-2.0 ?

Ping

**Comment by bastelfreak** [comment]
Any idea how we should proceed here? I would like to release an updated version with Apache-2.0. https://github.com/voxpupuli/puppet-graphite_powershell/pull/7

Can we stay with the MIT license for now?

**Comment by bastelfreak** [comment]
@daenney do you have any idea if we have to wait here for @stack72? His patch was really trivial:
https://github.com/voxpupuli/puppet-graphite_powershell/commit/a52c8c26d916a7d445ad4588c361e643a3f756bf

**Comment by alexjfisher** [comment]
If @liamjbennett is happy to relicense (and assuming he has the authority - the copyright might actually be owned by his employer for example), I think the specific commit from @stack72 isn't relevant in this case.

**Comment by daenney** [comment]
The commit by @stack72 is only changing the year in the LICENSE, I don't think that that in any way constitutes a contribution that would reasonable be covered by copyright.

As far as the rest of the module is concerned, assuming @liamjbennett got a proper OK from his employer to donate this module to VP I'm OK with relicensing this as you can reasonably expect a transfer of copyright in these cases. Granted, it's not explicit, but I don't think this would turn into an issue.

**Comment by liamjbennett** [comment]
Neither @stack72 or myself work for OpenTable any more so we cannot represent their interests on this. 

Maybe @fessyfoo can provide some input.

**Comment by juniorsysadmin** [comment]
@bastelfreak 
> Can we stay with the MIT license for now?
Yeah, just set MIT in metadata.json and close this PR

**Comment by alexjfisher** [comment]
@daenney 

> you can reasonably expect a transfer of copyright in these cases

Really?  I think this is a dangerous assumption.  Don't many people migrate their modules because they no longer have the time to maintain them/review PRs etc? I'd only assume they're migrating maintainership not ownership of copyright.

Also, the original maintainer (more often than not?) might not even be the sole copyright holder.

**Pull request closed without merging**
